# Este workflow actualiza el dataset en kaggle con los datos de la carpeta datos/procesados
name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepara Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instala dependencias
      run: |
        python -m pip install --upgrade pip
        pip install kaggle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Prepara credenciales de Kaggle
      run: |
        sh .github/utils/kaggle_credentials.sh
        sh .github/utils/kaggle_prep_data.sh
    - name: Sube datos a Kaggle
      env:
        HOY: date +"%Y-%m-%d"
      run: |
        kaggle datasets version -p ./datos/procesados/ -m "Actualización de ${HOY}"

