# Este workflow actualiza el dataset en kaggle con los datos de la carpeta datos/procesados
name: Sube a Kaggle

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepara Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instala dependencias
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas requests
    - name: Obtener datos y crear historias de pacientes
      run: |
        python src/datos/obtener_datos.py
        python src/datos/crear_historias_pacientes.py
    - name: Prepara credenciales de Kaggle
      env:
        KAGGLE_API_KEY: ${{ secrets.KAGGLE_API_KEY }}
      run: |
        sh .github/utils/kaggle_credentials.sh
    - name: Obtener la fecha de hoy
      id: fecha
      run: echo "::set-output name=date::$(TZ=\":America/Mexico_City\" date +\"%Y-%m-%d\")"
    - name: Sube datos a Kaggle
      run: |
        kaggle datasets version -p ./datos/procesados/ -m "Actualización de ${{steps.date.outputs.fecha}}"

