# Este workflow actualiza el dataset en kaggle con los datos de la carpeta datos/procesados
name: Sube a Kaggle

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepara Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instala dependencias
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas requests
    - name: Obtener datos y crear historias de pacientes
      run: |
        python src/datos/obtener_datos.py
        python src/datos/crear_historias_pacientes.py
    - name: Prepara credenciales de Kaggle
      env:
        KAGGLE_API_KEY: ${{ secrets.KAGGLE_API_KEY }}
      run: |
        sh .github/utils/kaggle_credentials.sh
    - name: Sube datos a Kaggle
      env:
        HOY: date +"%Y-%m-%d"
      run: |
        kaggle datasets version -p ./datos/procesados/ -m "Actualización de ${HOY}"

